//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_msg")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sender_id: i64,
    pub target_id: i64,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub msg_content: Vec<u8>,
    pub create_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
