//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::chat_msg::Entity as ChatMsg;
pub use super::user::Entity as User;
pub use super::user_relation_ship::Entity as UserRelationShip;
