client:
  ip: 0.0.0.0
  port: 20000

monitor:
  ip: 0.0.0.0
  port: 8888
  token: 123

http:
  ip: 0.0.0.0
  port: 12345

log:
  level: info
  filepath: ./logs
  filename: chat.log

# database config
database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: mircochat
  max_connection: 30
  min_connection: 5
  timeout: 5s

# redis config
redis:
  host: 172.16.112.2
  port: 6379
  database: 12
  username: root
  password: 123456