//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: String,
    pub user_name: String,
    pub nick_name: String,
    pub password: Option<String>,
    pub gender: i32,
    pub birthday: Option<i64>,
    pub phone: String,
    pub email: Option<String>,
    pub address: Option<String>,
    pub signature: Option<String>,
    pub facetype: Option<i32>,
    pub customface: Option<String>,
    pub customfacefmt: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub gropup_info: Option<Vec<u8>>,
    pub register_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
